//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ти матимеш змогу використовувати цю команду через {0} сек..
        /// </summary>
        public static string CooldownMessage {
            get {
                return ResourceManager.GetString("CooldownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка:.
        /// </summary>
        public static string ErrorHandleCommand {
            get {
                return ResourceManager.GetString("ErrorHandleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визначити точне місце розташування Зур-а я не можу.
        ///[Тут ти зможеш відшукати його місцезнаходження](https://whereisxur.com/)
        ///[Або тут](https://ftw.in/game/destiny-2/find-xur).
        /// </summary>
        public static string XurArriveEmbDesc {
            get {
                return ResourceManager.GetString("XurArriveEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ґардіан! Зур прибув у сонячну систему!.
        /// </summary>
        public static string XurArriveEmbTitle {
            get {
                return ResourceManager.GetString("XurArriveEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Він просто зник! :open_mouth:.
        /// </summary>
        public static string XurLeaveEmbDesc {
            get {
                return ResourceManager.GetString("XurLeaveEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увага! Зур покинув сонячну систему..
        /// </summary>
        public static string XurLeaveEmbTitle {
            get {
                return ResourceManager.GetString("XurLeaveEmbTitle", resourceCulture);
            }
        }
    }
}
